### ISSUE TITLE
Get a cut of 21.1 and test it with the operator

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach-operator#338] opened 2021-03-15 17:41 UTC
We need to get a release candidate / beta of the 21.1 release to make sure we will be able to support that release when it drops. @isaactwong who would I need to work with to get that process started?

cc: @johnrk @taroface @chrislovecnm @alinadonisa

**Comment by keith-mcclellan** [comment] 2021-03-19 16:23
@rail can you help us with this? we're going to need an RC/Beta of 21.1 with a clean build tag (v21.1.0 for example)

**Comment by rail** [comment] 2021-03-19 16:29
> @rail can you help us with this? we're going to need an RC/Beta of 21.1 with a clean build tag (v21.1.0 for example)

Can you elaborate on this? What do you mean by "a clean build tag"? Where it should be set and how it will be used?

My concern is that we may create some confusion around the situation that v21.1 is actually a beta.

**Comment by keith-mcclellan** [comment] 2021-03-19 16:54
the operator parses the build tag to determine the version so we can make upgrade decisions. What does the build tag usually look like for a beta?  (what returns under Build Tag: from `cockroach --version`)

**Comment by rail** [comment] 2021-03-19 16:59
I checked agains one of the 20.2 betas, and I think it'll be similar for 21.1:
```shell
$ docker run -ti  cockroachdb/cockroach-unstable:v20.2.0-beta.4 version
Build Tag:        v20.2.0-beta.4
Build Time:       2020/10/06 17:09:09
Distribution:     CCL
Platform:         linux amd64 (x86_64-unknown-linux-gnu)
Go Version:       go1.13.14
C Compiler:       gcc 6.3.0
Build Commit ID:  305ee38104e147c971fe21139082eb81614b4766
Build Type:       release
```

**Comment by keith-mcclellan** [comment] 2021-03-19 17:00
@alinadonisa does our upgrade handle parsing build tags if there's text after the version number?

**Comment by rail** [comment] 2021-04-12 15:50
Marking as duplicate of #379, it has more information.

**Closed by rail** 2021-04-12 15:50 UTC
Labels: enhancement, next release, upgrades/updates
