### ISSUE TITLE
The self-signer rotate pod errors out when setting automountServiceAccountToken to false

### ISSUE THREAD

**Issue by rubensymc** [cockroachdb/cockroach-operator#974] opened 2023-04-03 18:19 UTC
Surprisingly, there are no errors in the logs when the job runs and fails after adding "automountServiceAccountToken" setting:

```
NAME                                                              READY   STATUS      RESTARTS   AGE
cockroachdb-0                                                 1/1     Running     0          26h
cockroachdb-1                                                 1/1     Running     0          26h
cockroachdb-2                                                 1/1     Running     0          26h
cockroachdb-init-ccn4r                                        0/1     Completed   0          29s
cockroachdb--rotate-self-signer-client-manual-rotation-fxjnq   0/1     Error       0          2s
$ k logs -f cockroachdb-rotate-self-signer-client-manual-rotation-fxjnq
```

**Comment by udnay** [comment] 2023-04-04 13:10
@prafull01 can you take a look?

**Comment by prafull01** [comment] 2023-04-07 03:43
@rubensymc Thank you for raising this issue.

Could you please provide minimum reproducible steps to reproduce this issue on my end. Till now I am not able to reproduce this issue at my end by enabling/disabling `automountServiceAccountToken`

Also, Can you please provide the following information:
1. Yaml of the `crdbclusters.crdb.cockroachlabs.com`
2. Yaml of the rotate-self-signer-client Job.

**Comment by rubensymc** [comment] 2023-04-11 15:34
Hello @prafull01 

Steps to reproduce:
1. Add `automountServiceAccountToken: false` to the pod spec in cronjob template: `charts/cockroachdb/templates/cronjob-client-node-certSelfSigner.yaml`
2. Run helm upgrade to apply changes to the cockroachdb helm release
3. Spin up a pod from the cronjob to test out changes: `k create job --from=cronjob/cockroachdb-rotate-self-signer-client cockroachdb-rotate-self-signer-client-test-1`
4. The pod should error out with no messages available in the pod logs

We do not have crdbclusters available as we are not running cockroachdb operator:
```
error: the server doesn't have a resource type "crdbclusters"
```

**Comment by prafull01** [comment] 2023-04-11 18:41
Thank you for the steps. This issue is not related to the `cockroach-operator` repo. It is related to the [helm-charts](https://github.com/cockroachdb/helm-charts) repo, so we should move this issue to the other repo.

**Comment by prafull01** [comment] 2023-04-12 08:45
You can opt out of automounting API credentials on /var/run/secrets/kubernetes.io/serviceaccount/token for a service account by setting automountServiceAccountToken: false on the Pod.

Once you set this, the pod will not have capability to communicate with the apiserver. This is done for the pods which doesn't require any communication with the apiserver in their functioning. Here, you can disable `automountServiceAccountToken` in the cockroachdb statefulset because cockroachdb pods doesn't require to communicate with the apiserver.

The cronjob `cockroachdb-rotate-self-signer-client` needs to communicate with the apiserver so that it can rotate the client certificate and store those certificates in the kubernetes secret.

The reason for no error is that on start of the self-signer utility, we try to connect with the cluster using function `ctrl.GetConfigOrDie()` fails because it can't connect with the kubernetes api server. For the self signer utility pods you can't set the `automountServiceAccountToken: false` as it is critical for the functioning for this utility to run.

**Comment by rubensymc** [comment] 2023-04-12 18:08
Sounds like this is an expected behavior which makes sense. Now that I have that confirmation from you please feel free to close this off.

**Comment by prafull01** [comment] 2023-04-12 18:29
Closing this in favour of above comment.

**Closed by prafull01** 2023-04-12 18:29 UTC
Labels: bug
