### ISSUE TITLE
rbac.authorization.k8s.io/v1beta1 RoleBinding is deprecated in v1.17+

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach-operator#312] opened 2021-02-02 14:12 UTC
```
tobias@td:~/go/src/github.com/cockroachdb/cockroach$ minikube kubectl -- apply -f https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/manifests/operator.yaml
clusterrole.rbac.authorization.k8s.io/cockroach-database-role created
serviceaccount/cockroach-database-sa created
clusterrolebinding.rbac.authorization.k8s.io/cockroach-database-rolebinding created
role.rbac.authorization.k8s.io/cockroach-operator-role created
clusterrolebinding.rbac.authorization.k8s.io/cockroach-operator-rolebinding created
clusterrole.rbac.authorization.k8s.io/cockroach-operator-role created
serviceaccount/cockroach-operator-sa created
Warning: rbac.authorization.k8s.io/v1beta1 RoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 RoleBinding
rolebinding.rbac.authorization.k8s.io/cockroach-operator-default created
deployment.apps/cockroach-operator created
```

**Comment by johnrk** [comment] 2021-02-04 18:33
@chrislovecnm , is this being resolved with the other security work that we're doing? What are your thoughts on prioritizing?

**Comment by chrislovecnm** [comment] 2021-02-04 19:19
This is a duplicate issue. Can we fold it into the CRD issue?

**Comment by chrislovecnm** [comment] 2021-02-05 13:40
This is a duplicate of https://github.com/cockroachdb/cockroach-operator/issues/313

both are generated by kubebuilder automatically.

**Comment by keith-mcclellan** [comment] 2021-03-15 16:30
this is being fixed in https://github.com/cockroachdb/cockroach-operator/pull/329 now that we've refactored for 1.20.  Closing this as we're tracking that progress in a different issue.

**Closed by keith-mcclellan** 2021-03-15 16:30 UTC
