### ISSUE TITLE
Major upgrades after scaling fail.

### ISSUE THREAD

**Issue by alyshanjahani-crl** [cockroachdb/cockroach-operator#473] opened 2021-04-29 15:25 UTC
I created a 5 node cluster (on v20.1.1) w/ the operator. Then Scaled to 3.
Then change the image to v20.2.1.
Let operator update the image of the crdb pods in the cluster.
Then `set cluster setting cluster.preserve_downgrade_option=''` to finalize the upgrade.

The finalization was unsuccessful, relevant logs from the crdb pods:
```
I210429 15:17:30.338514 1530 server/server_update.go:52 ⋮ [n1] failed attempt to upgrade cluster version, error: node 4 not running (‹NODE_STATUS_DEAD›), cannot determine version
```

```
**I210429 15:24:01.902099 71244 rpc/nodedialer/nodedialer.go:160 ⋮ [n2] unable to connect to n5: failed to connect to n5 at ‹cockroachdb-4.cockroachdb.default:26258›: ‹initial connection heartbeat failed›: ‹rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup cockroachdb-4.cockroachdb.default on 10.3.240.10:53: no such host"›
I210429 15:24:03.702154 71284 rpc/nodedialer/nodedialer.go:160 ⋮ [n2] unable to connect to n4: failed to connect to n4 at ‹cockroachdb-3.cockroachdb.default:26258›: ‹initial connection heartbeat failed›: ‹rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup cockroachdb-3.cockroachdb.default on 10.3.240.10:53: no such host"**
```

**Comment by johnrk** [comment] 2021-05-05 15:20
@alinadonisa will investigate this issue.

**Comment by alinadonisa** [comment] 2021-05-05 19:13
@alyshanjahani-crl  when you scaled to 3 nodes, node 4 and 5 were deleted, but somehow the cockroach nodes that remained still try to connect to the  deleted  ones. The problem is on decommission, the node 4 and 5 did not drained correctly. @chrisseto  do you have a fix for this?

**Comment by keith-mcclellan** [comment] 2021-05-12 19:03
@alinadonisa how is the operator getting the list of nodes that need to be upgraded?

**Comment by alinadonisa** [comment] 2021-05-13 06:10
@keith-mcclellan because we are using RollingUpdate strategy of the Statefulset, we are making the checks for each pod in the sts iterating through sts.Spec.Replicas.
 We get each po using:
```golang
podName := fmt.Sprintf("%s-%d", stsName, podNumber)

crdbPod, err := clientset.CoreV1().Pods(stsNamespace).Get(update.ctx, podName, metav1.GetOptions{})		
```

**Comment by keith-mcclellan** [comment] 2021-05-13 13:40
When you scale down from 5 to 3, how do we remove those nodes from the cockroachdb cluster? I thought we were doing a graceful `cockroach node decommission`?

**Comment by alinadonisa** [comment] 2021-05-13 14:05
@keith-mcclellan, yes... I misunderstood. I thought you are asking about the upgrade code. The decommission it is actually code from the database project added by @chrisseto. It uses  the replica from the statefulset.

```golang
// Scale down CRDB if need be. Do it gracefully one by one for safety
	for crdbScale > scale {
		oneOff := crdbScale - 1

		s.Logger.V(int(zapcore.DebugLevel)).Info("scaling down stateful set", "have", crdbScale, "want", oneOff)

		// TODO (chrisseto): If decommissioning fails due to a timeout
		// recommission that node before failing this job.
		// Making use of the on finish hook is likely ideal?
		if err := s.Drainer.Decommission(ctx, oneOff); err != nil {
			return err
		}

		if err := s.CRDB.SetReplicas(ctx, oneOff); err != nil {
			return err
		}
```
 On s.Drainer.Decommission method we are always getting the last node from the StatefulSet and exec the drain on it.

**Comment by keith-mcclellan** [comment] 2021-05-18 17:57
This code isn't actually getting executed, I just reproduced this bug myself.  When I change the node count from 5 > 3 rather than seeing decommissioned nodes, I see failed nodes. I pulled the operator logs and it looks like the decommission actor is erroring out. 

```{"level":"error","ts":1621359829.9039705,"logger":"action","msg":"decomission failed","action":"decommission","CrdbCluster":"cockroachdb/crdb-tls-example","error":"failed to start draining node 5: failed to stream execution results back: command terminated with exit code 1","errorVerbose":"failed to start draining node 5: failed to stream execution results back: command terminated with exit code 1\n(1) attached stack trace\n  -- stack trace:\n  | github.com/cockroachdb/cockroach-operator/pkg/scale.(*CockroachNodeDrainer).executeDrainCmd\n  | \tpkg/scale/drainer.go:208\n  | [...repeated from below...]\nWraps: (2) failed to start draining node 5\nWraps: (3) attached stack trace\n  -- stack trace:\n  | github.com/cockroachdb/cockroach-operator/pkg/scale.CockroachExecutor.Exec\n  | \tpkg/scale/executor.go:57\n  | github.com/cockroachdb/cockroach-operator/pkg/scale.(*CockroachNodeDrainer).executeDrainCmd\n  | \tpkg/scale/drainer.go:207\n  | github.com/cockroachdb/cockroach-operator/pkg/scale.(*CockroachNodeDrai..```

![Screen Shot 2021-05-18 at 1 51 35 PM](https://user-images.githubusercontent.com/4730669/118700012-2a969100-b7e0-11eb-8ec1-60de81addcc3.png)


[operator.log](https://github.com/cockroachdb/cockroach-operator/files/6503306/operator.log)

It looks to me like we're stopping the pod THEN running decommission, rather than running the command, waiting for it to complete, and then stopping the pod.  Not sure how we got in this state but this is definitely a release blocker.

**Comment by udnay** [comment] 2021-05-18 17:58
This is the e2e test that's failing as well, afaik

**Comment by keith-mcclellan** [comment] 2021-05-18 17:59
Well that explains a lot, something

**Comment by udnay** [comment] 2021-05-18 18:03
<img width="2656" alt="Screen Shot 2021-05-18 at 2 02 35 PM" src="https://user-images.githubusercontent.com/1341716/118701572-db516000-b7e1-11eb-8ae6-23cc3443cd44.png">

**Closed** 2021-05-20 14:39 UTC
Labels: bug, release-blocker
