### ISSUE TITLE
applying crd requires turning off client side validation (--validate=false)

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#23] opened 2020-05-22 19:59 UTC
When applying the CRD (kubectl apply -f config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml), it requires using the --validate=false flag.

At the moment, I receive this error:
`error: error validating "config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml": error validating data: ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.dataStore.properties.emptyDir.properties.sizeLimit): unknown field "x-kubernetes-int-or-string" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps; if you choose to ignore these errors, turn validation off with --validate=false`

**Environment:**
Running on a k8s cluster on GKE, following these instructions: https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes.html

**kubectl version:**
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by vladdy** [comment] 2020-05-22 20:45
This is the expected behavior due to new functionality added into k8s libraries. Did you want something to be done about it?

**Comment by chrislovecnm** [comment] 2020-07-11 16:07
I am not having this issue with my version of kubectl.  I think this was a version issue on your machine.  We can keep this open and have someone else verify that this is fixed.

**Comment by chrislovecnm** [comment] 2020-07-14 22:49
@johnrk can you please test this?  I believe this is resolved by using the latest version of GKE and kubectl.

**Closed** 2020-07-15 14:30 UTC
Labels: bug
