### ISSUE TITLE
Operator on OpenShift: Pods do not appear in Web Console View

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#440] opened 2021-04-26 18:34 UTC
In the OpenShift web console, the "Pods" page returns an empty view. 

**Repro steps:**

- In the OpenShift web console, created CrdbCluster with CockroachDB Version: "v20.2.7"

**Expected Result:**

- In the "Pods" page, I would expect to see 3 pods that I can explore in detail.

**Actual Result:** 

- I received an empty. Screenshots attached.
- When running oc get pods, one can see three pods were created. The deployment succeeded, so this could be an OpenShift issue.

<img width="1920" alt="Screen Shot 2021-04-26 at 2 30 16 PM" src="https://user-images.githubusercontent.com/1663752/116133184-6a180480-a69c-11eb-80b3-fb49fb93753c.png">
<img width="1920" alt="Screen Shot 2021-04-26 at 2 30 03 PM" src="https://user-images.githubusercontent.com/1663752/116133185-6a180480-a69c-11eb-9b6b-29d0ae741eef.png">
<img width="1920" alt="Screen Shot 2021-04-26 at 2 29 53 PM" src="https://user-images.githubusercontent.com/1663752/116133187-6ab09b00-a69c-11eb-847f-34d6b14651d2.png">

**Comment by johnrk** [comment] 2021-05-04 17:29
@keith-mcclellan , if this issue is still active, we might have to consider this a release blocker. Users would be confused by this experience.

**Comment by keith-mcclellan** [comment] 2021-05-20 15:35
I just tested this on the latest openshift and I couldn't reproduce this, so I think it's safe to say this was an OpenShift bug and not an operator bug.  Closing because I couldn't reproduce

**Closed by keith-mcclellan** 2021-05-20 15:35 UTC
Labels: bug, release-blocker
