### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#272] opened 2021-01-05 16:12 UTC
We are encountering a new problem with TeamCity.  When the e2e tests start kind we are getting the following error.  We are using kind to start a k8s cluster to test the operator.  We are getting 

```
  FAIL: //e2e:go_default_test (see /home/agent/.cache/bazel/_bazel_agent/db69d2667a2397aa0eb10c3ba2d30715/execroot/com_github_coachroachdb_cockroach_operator/bazel-out/k8-fastbuild/testlogs/e2e/go_default_test/test.log)
14:30:35
  INFO: From Testing //e2e:go_default_test:
14:30:35
  ==================== Test output for //e2e:go_default_test:
14:30:35
  Up(): startin kind cluster...
14:30:35
  14:30:35
  I1228 21:30:09.865254      47 app.go:87] ID for this run: "ee2d2425-013b-4acc-ae5d-491e221e75d6"
14:30:35
  Up(): creating kind cluster...
14:30:35
  14:30:35
  WARNING: --loglevel is deprecated, please switch to -v and -q!
14:30:35
  Creating cluster "test" ...
14:30:35
   • Ensuring node image (kindest/node:v1.17.0)     ...
14:30:35
   ✓ Ensuring node image (kindest/node:v1.17.0)   
14:30:35
   • Preparing nodes      ...
14:30:35
   ✓ Preparing nodes    
14:30:35
   • Writing configuration     ...
14:30:35
   ✗ Writing configuration   
14:30:35
  ERROR: failed to create cluster: failed to get IPs for node: test-control-plane: file should only be one line, got 2 lines
14:30:35
  Error: exit status 1
14:30:35
  panic: exit status 1
14:30:35
  14:30:35
  goroutine 1 [running]:
14:30:35
  github.com/cockroachdb/cockroach-operator/e2e.TestMain(0xc0001a6a80)
14:30:35
    e2e/e2e_test.go:80 +0x5b1
14:30:35
  main.main()
14:30:35
    bazel-out/k8-fastbuild/bin/e2e/go_default_test_/testmain.go:112 +0x208
```

Reading issues in the kind repository, this problem may be related to the docker setup.  Was the docker setup changed with TeamCity?  What was updated recently with TeamCity?

None of our PRs are passing testing currently.  See https://github.com/cockroachdb/cockroach-operator/pull/244

**Comment by rickystewart** [comment] 2021-01-05 18:20
I googled the error and found [this bug](https://github.com/kubernetes-sigs/kind/issues/1350), which looks related. That was apparently fixed with [this PR](https://github.com/kubernetes-sigs/kind/pull/1415). That predates [the version of `kind`](https://github.com/cockroachdb/cockroach-operator/blob/master/hack/bin/deps.bzl#L239) that you're using. Is it possible that upgrading to the latest `kind`(in that file, `hack/bin/deps.bzl`) would fix this?

**Comment by rickystewart** [comment] 2021-01-05 18:31
Running [a build](https://teamcity.cockroachdb.com/viewQueued.html?itemId=2560153) to test that hypothesis.

**Comment by rickystewart** [comment] 2021-01-05 18:39
Hmm. Now a slightly different, but definitely related error:

```
RROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: file should only be one line, got 2 lines
```

Still investigating.

**Comment by rickystewart** [comment] 2021-01-05 19:20
Out of curiosity I tried to run a test on [the new agent image](https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=2560173&_focus=731) and it doesn't fail in the same way. I assume the new image picks up a new version of Docker which isn't affected in the same way. Some tests still fail though. I'm not sure if this is expected.

I'm going to push this new agent image today anyway, so I'll just bump this when I do.

**Comment by chrislovecnm** [comment] 2021-01-06 16:06
@rickystewart any progress?  Do you think it is a TeamCity agent issue?  I am thinking it is related to the Agent and not our code.

**Comment by rickystewart** [comment] 2021-01-06 16:14
That's my suspicion. I'm updating the agents now, and we'll see what that improves.

**Comment by rickystewart** [comment] 2021-01-06 20:20
The rollout of the new agents is completed. Are you seeing an improvement now?

**Comment by chrislovecnm** [comment] 2021-01-11 16:13
@rickystewart same issue https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_CockroachOperator_EndToEnd/2569169?buildTab=log&focusLine=3&linesState=494

Next time please feel free to push a dummy PR

cc: @JuanLeon1

**Comment by rickystewart** [comment] 2021-01-12 18:33
Small update: I've created a dedicated machine for investigating this, and have found the following:

1. The issue is trivially reproducible by cloning `cockroach-operator` on the machine and running `bazel test //e2e/...`.
2. Upgrading `kind` as in #276 makes the problem manifest slightly differently: `failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: file should only be one line, got 2 lines`
3. Upgrading both `kind` and `kubectl` doesn't do anything to fix the issue.
4. However, I haven't been able to reproduce outside the context of the `bazel test`. i.e., after running the test, this command succeeds:

```
agent@instance-1:~/cockroach-operator$ PATH="bazel-out/k8-fastbuild/bin/hack/bin:$PATH" kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.19.1) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:
kubectl cluster-info --context kind-kind
Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/
agent@instance-1:~/cockroach-operator
```

So my question would be, why does this fail inside the test but not outside it.

**Comment by chrislovecnm** [comment] 2021-01-12 18:52
> The issue is trivially reproducible by cloning cockroach-operator on the machine and running bazel test //e2e/....

What do you mean?

Also what has been upgraded?  This worked previously ...

**Comment by rickystewart** [comment] 2021-01-12 19:02
> What do you mean?

I'm just saying the issue has nothing to do with TeamCity or any of the surrounding infrastructure. If you take a fresh build machine, clone `cockroach-operator`, and run `bazel test //e2e/...`, the issue reproduces. So it reproduces on our build machines but isn't related to TeamCity, the build configuration, etc.

> Also what has been upgraded? This worked previously ...

I don't know when this was last working for you, but not much has *explicitly* changed recently. You can check [the log](https://github.com/cockroachdb/cockroach/commits/master/build/packer). Problem is that each agent update can, without us explicitly specifying anything, pick up new versions of tools or make arbitrary other changes that can cause breakages.

If you give me an idea when the build used to work, I can try digging up an old image and get a VM running so we can compare what's changed. Not sure if that will help the investigation.

**Comment by chrislovecnm** [comment] 2021-01-12 19:37
> I'm just saying the issue has nothing to do with TeamCity or any of the surrounding infrastructure. If you take a fresh build machine, clone cockroach-operator, and run bazel test //e2e/..., the issue reproduces. So it reproduces on our build machines but isn't related to TeamCity, the build configuration, etc

Can you give me the machine type that you are running it on?

**Comment by rickystewart** [comment] 2021-01-12 19:48
> Can you give me the machine type that you are running it on? I am running it on a virtual machine in GCP without any issues.

I'm using the latest agent image, `teamcity-agent-1609866058` in the `cockroach-teamcity-public-prs` GCP project.

**Comment by chrislovecnm** [comment] 2021-01-12 20:29
I am pretty certain that I do not have access to that project or VM template

**Comment by chrislovecnm** [comment] 2021-03-11 22:43
https://github.com/cockroachdb/cockroach-operator/pull/333 should fix this

**Comment by chrislovecnm** [comment] 2021-03-16 18:31
So this problem is fixed, but we are having an issue with the job.  @alinadonisa is working on this in a different PR.

@keith-mcclellan / @johnrk can we close this issue?

**Comment by keith-mcclellan** [comment] 2021-03-16 18:38
Is there an issue associated with the PR that @alinadonisa is working on? If yes we can close this. If not let's reference the PR here and keep the issue open until that work is complete.

**Closed** 2021-03-17 16:47 UTC
Labels: next release
